import HD1 from "../assets/HD1.png";
import HD2 from "../assets/HD2.png";
import HD3 from "../assets/HD3.png";
import HD4 from "../assets/HD4.png";
import HD5 from "../assets/HD5.png";
import HD6 from "../assets/HD6.png";
import HD7 from "../assets/HD7.png";
import HD8 from "../assets/HD8.png";
import D1 from "../assets/D1.png";
import D2 from "../assets/D2.png";
import D3 from "../assets/D3.png";
import D4 from "../assets/D4.png";

export const fallbackDoctors = [
  {
    id: "6a3820c82cecc9714b826111",
    _id: "6a3820c82cecc9714b826111",
    name: "Dr. Sarah Johnson",
    specialization: "Cardiologist",
    speciality: "Cardiologist",
    image: HD1,
    imageUrl: HD1,
    experience: "12 years",
    qualifications: "MBBS, MD (Cardiology)",
    location: "City Hospital, Block A",
    about: "Expert in heart rhythm, cardiac care, and coronary interventions.",
    fee: 700,
    price: 700,
    available: true,
    availability: "Available",
    success: "98%",
    patients: "2k+",
    rating: 4.9,
    email: "sarah@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826112",
    _id: "6a3820c82cecc9714b826112",
    name: "Dr. Michael Chen",
    specialization: "Neurologist",
    speciality: "Neurologist",
    image: HD2,
    imageUrl: HD2,
    experience: "15 years",
    qualifications: "MBBS, DM (Neurology)",
    location: "NeuroCare Center, 2nd Floor",
    about: "Expert in migraine, stroke, epilepsy and neuro disorders.",
    fee: 900,
    price: 900,
    available: true,
    availability: "Available",
    success: "89%",
    patients: "1.8k+",
    rating: 4.5,
    email: "michael@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826113",
    _id: "6a3820c82cecc9714b826113",
    name: "Dr. Emily Rodriguez",
    specialization: "Pediatrician",
    speciality: "Pediatrician",
    image: HD3,
    imageUrl: HD3,
    experience: "8 years",
    qualifications: "MBBS, DCH",
    location: "Sunrise Pediatrics, Sector 12",
    about: "Child specialist focusing on growth, nutrition, and immunity.",
    fee: 500,
    price: 500,
    available: true,
    availability: "Available",
    success: "97%",
    patients: "3.2k+",
    rating: 4.8,
    email: "emily@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826114",
    _id: "6a3820c82cecc9714b826114",
    name: "Dr. James Wilson",
    specialization: "Orthopedic Surgeon",
    speciality: "Orthopedic Surgeon",
    image: HD4,
    imageUrl: HD4,
    experience: "18 years",
    qualifications: "MBBS, MS (Orthopedics)",
    location: "OrthoPlus Clinic",
    about: "Joint replacement & sports injury expert.",
    fee: 1200,
    price: 1200,
    available: true,
    availability: "Available",
    success: "92%",
    patients: "1.5k+",
    rating: 4.6,
    email: "james@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826115",
    _id: "6a3820c82cecc9714b826115",
    name: "Dr. Priya Sharma",
    specialization: "Dermatologist",
    speciality: "Dermatologist",
    image: HD5,
    imageUrl: HD5,
    experience: "10 years",
    qualifications: "MBBS, DDV",
    location: "SkinCare Hub, Green Plaza",
    about: "Acne, pigmentation, hair fall & skin treatment specialist.",
    fee: 600,
    price: 600,
    available: true,
    availability: "Available",
    success: "94%",
    patients: "2.7k+",
    rating: 4.7,
    email: "priya@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826116",
    _id: "6a3820c82cecc9714b826116",
    name: "Dr. Robert Brown",
    specialization: "Psychiatrist",
    speciality: "Psychiatrist",
    image: HD6,
    imageUrl: HD6,
    experience: "20 years",
    qualifications: "MBBS, MD (Psychiatry)",
    location: "MindWell Clinic",
    about: "Mood disorders, anxiety, therapy & behavioral care.",
    fee: 1100,
    price: 1100,
    available: true,
    availability: "Available",
    success: "90%",
    patients: "3.1k+",
    rating: 4.4,
    email: "robert@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826117",
    _id: "6a3820c82cecc9714b826117",
    name: "Dr. Lisa Wang",
    specialization: "Gynecologist",
    speciality: "Gynecologist",
    image: HD7,
    imageUrl: HD7,
    experience: "11 years",
    qualifications: "MBBS, DGO",
    location: "Women's Health Center",
    about: "Infertility, antenatal & gyne care expert.",
    fee: 750,
    price: 750,
    available: true,
    availability: "Available",
    success: "96%",
    patients: "2.4k+",
    rating: 4.9,
    email: "lisa@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826118",
    _id: "6a3820c82cecc9714b826118",
    name: "Dr. David Kim",
    specialization: "Oncologist",
    speciality: "Oncologist",
    image: HD8,
    imageUrl: HD8,
    experience: "16 years",
    qualifications: "MBBS, DM (Oncology)",
    location: "CancerCare Institute",
    about: "Specialist in chemotherapy, targeted therapy & cancer care.",
    fee: 1500,
    price: 1500,
    available: true,
    availability: "Available",
    success: "93%",
    patients: "2.9k+",
    rating: 4.6,
    email: "david@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826119",
    _id: "6a3820c82cecc9714b826119",
    name: "Dr. Rohan Mehta",
    specialization: "ENT Specialist",
    speciality: "ENT Specialist",
    image: D2,
    imageUrl: D2,
    experience: "9 years",
    qualifications: "MBBS, MS (ENT)",
    location: "Apex ENT Hospital",
    about: "Specialist in sinusitis, hearing loss, and vocal issues.",
    fee: 650,
    price: 650,
    available: true,
    availability: "Available",
    success: "91%",
    patients: "1.6k+",
    rating: 4.5,
    email: "rohan@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826120",
    _id: "6a3820c82cecc9714b826120",
    name: "Dr. Ananya Roy",
    specialization: "Ophthalmologist",
    speciality: "Ophthalmologist",
    image: D3,
    imageUrl: D3,
    experience: "13 years",
    qualifications: "MBBS, MS (Ophthalmology)",
    location: "ClearVision Eye Clinic",
    about: "Cataract surgery, LASIK, and glaucoma management.",
    fee: 800,
    price: 800,
    available: true,
    availability: "Available",
    success: "97%",
    patients: "2.2k+",
    rating: 4.8,
    email: "ananya@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826121",
    _id: "6a3820c82cecc9714b826121",
    name: "Dr. Jason Lee",
    specialization: "Gastroenterologist",
    speciality: "Gastroenterologist",
    image: D4,
    imageUrl: D4,
    experience: "14 years",
    qualifications: "MBBS, DM (Gastro)",
    location: "Digestive Health Clinic",
    about: "Digestive health, liver care, endoscopy and IBD specialist.",
    fee: 950,
    price: 950,
    available: true,
    availability: "Available",
    success: "95%",
    patients: "1.9k+",
    rating: 4.7,
    email: "jason@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826122",
    _id: "6a3820c82cecc9714b826122",
    name: "Dr. Sneha Verma",
    specialization: "General Physician",
    speciality: "General Physician",
    image: D1,
    imageUrl: D1,
    experience: "7 years",
    qualifications: "MBBS",
    location: "CareFirst Clinic",
    about: "General health, fever, infections, diabetes and routine checkups.",
    fee: 400,
    price: 400,
    available: true,
    availability: "Available",
    success: "99%",
    patients: "4k+",
    rating: 4.9,
    email: "sneha@medicare.com",
  }
];
