import D4 from "../assets/D4.png";
import D5 from "../assets/D5.png";
import D6 from "../assets/D6.png";
import D7 from "../assets/D7.png";
import D8 from "../assets/D8.png";
import D9 from "../assets/D9.png";
import D10 from "../assets/D10.png";
import D11 from "../assets/D11.png";
import D12 from "../assets/D12.png";
import HD5 from "../assets/HD5.png";

export const fallbackDoctors = [
  {
    id: "6a3820c82cecc9714b826111",
    _id: "6a3820c82cecc9714b826111",
    name: "Dr. Rajesh Kumar",
    specialization: "Cardiologist",
    speciality: "Cardiologist",
    image: D6,
    imageUrl: D6,
    experience: "16 years",
    qualifications: "MBBS, MD (General Medicine), DM (Cardiology)",
    location: "Indiranagar, Bangalore",
    about: "Senior Interventional Cardiologist specializing in coronary interventions, hypertension, and preventive cardiac wellness.",
    fee: 800,
    price: 800,
    available: true,
    availability: "Available",
    patients: "3.5k+",
    rating: 4.9,
    email: "rajesh.kumar@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826112",
    _id: "6a3820c82cecc9714b826112",
    name: "Dr. Suresh Reddy",
    specialization: "Neurologist",
    speciality: "Neurologist",
    image: D7,
    imageUrl: D7,
    experience: "15 years",
    qualifications: "MBBS, DM (Neurology), DNB",
    location: "Koramangala, Bangalore",
    about: "Consultant Neurologist expert in chronic migraines, epilepsy, neuromuscular disorders, and acute stroke management.",
    fee: 900,
    price: 900,
    available: true,
    availability: "Available",
    patients: "2.8k+",
    rating: 4.8,
    email: "suresh.reddy@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826113",
    _id: "6a3820c82cecc9714b826113",
    name: "Dr. Ananya Deshmukh",
    specialization: "Pediatrician",
    speciality: "Pediatrician",
    image: D4,
    imageUrl: D4,
    experience: "11 years",
    qualifications: "MBBS, MD (Pediatrics), DCH",
    location: "Whitefield, Bangalore",
    about: "Child specialist focused on pediatric nutrition, developmental milestones, vaccinations, and seasonal allergies.",
    fee: 600,
    price: 600,
    available: true,
    availability: "Available",
    patients: "4.2k+",
    rating: 4.9,
    email: "ananya.deshmukh@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826114",
    _id: "6a3820c82cecc9714b826114",
    name: "Dr. Vikram Hegde",
    specialization: "Orthopedic Surgeon",
    speciality: "Orthopedic Surgeon",
    image: D8,
    imageUrl: D8,
    experience: "18 years",
    qualifications: "MBBS, MS (Orthopaedics), M.Ch (Ortho)",
    location: "Jayanagar, Bangalore",
    about: "Expert in robotic joint replacement, arthroscopic knee reconstruction, and sports traumatology.",
    fee: 1000,
    price: 1000,
    available: true,
    availability: "Available",
    patients: "3.1k+",
    rating: 4.7,
    email: "vikram.hegde@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826115",
    _id: "6a3820c82cecc9714b826115",
    name: "Dr. Priya Sharma",
    specialization: "Dermatologist",
    speciality: "Dermatologist",
    image: HD5,
    imageUrl: HD5,
    experience: "10 years",
    qualifications: "MBBS, MD (Dermatology, Venereology & Leprosy)",
    location: "HSR Layout, Bangalore",
    about: "Clinical and aesthetic dermatologist specializing in acne scar treatments, pigmentation, and hair-loss therapies.",
    fee: 700,
    price: 700,
    available: true,
    availability: "Available",
    patients: "2.9k+",
    rating: 4.8,
    email: "priya.sharma@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826116",
    _id: "6a3820c82cecc9714b826116",
    name: "Dr. Arvind Swaminathan",
    specialization: "Psychiatrist",
    speciality: "Psychiatrist",
    image: D9,
    imageUrl: D9,
    experience: "14 years",
    qualifications: "MBBS, MD (Psychiatry), DPM",
    location: "Malleshwaram, Bangalore",
    about: "Neuropsychiatrist treating anxiety disorders, clinical depression, adult ADHD, and stress management.",
    fee: 850,
    price: 850,
    available: true,
    availability: "Available",
    patients: "2.2k+",
    rating: 4.6,
    email: "arvind.swami@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826117",
    _id: "6a3820c82cecc9714b826117",
    name: "Dr. Sunita Kulkarni",
    specialization: "Gynecologist",
    speciality: "Gynecologist",
    image: D5,
    imageUrl: D5,
    experience: "16 years",
    qualifications: "MBBS, MS (Obstetrics & Gynaecology), DGO",
    location: "Bellandur, Bangalore",
    about: "Senior Obstetrician and High-Risk Pregnancy Specialist with vast experience in minimally invasive laparoscopic surgeries.",
    fee: 750,
    price: 750,
    available: true,
    availability: "Available",
    patients: "4.5k+",
    rating: 4.9,
    email: "sunita.kulkarni@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826118",
    _id: "6a3820c82cecc9714b826118",
    name: "Dr. Karthik Venkatesh",
    specialization: "General Physician",
    speciality: "General Physician",
    image: D12,
    imageUrl: D12,
    experience: "12 years",
    qualifications: "MBBS, MD (Internal Medicine)",
    location: "BTM Layout, Bangalore",
    about: "Consultant Physician focused on lifestyle diseases, type-2 diabetes reversal, hypertension, and infectious diseases.",
    fee: 500,
    price: 500,
    available: true,
    availability: "Available",
    patients: "5.1k+",
    rating: 4.8,
    email: "karthik.v@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b826119",
    _id: "6a3820c82cecc9714b826119",
    name: "Dr. Sanjay Bhattacharya",
    specialization: "Oncologist",
    speciality: "Oncologist",
    image: D7,
    imageUrl: D7,
    experience: "19 years",
    qualifications: "MBBS, MD (Medicine), DM (Medical Oncology)",
    location: "Sadashivanagar, Bangalore",
    about: "Medical Oncologist with deep expertise in targeted immunotherapy, chemotherapy regimens, and solid tumor oncology.",
    fee: 1200,
    price: 1200,
    available: true,
    availability: "Available",
    patients: "1.9k+",
    rating: 4.9,
    email: "sanjay.b@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b82611a",
    _id: "6a3820c82cecc9714b82611a",
    name: "Dr. Deepa Ranganathan",
    specialization: "ENT Specialist",
    speciality: "ENT Specialist",
    image: D10,
    imageUrl: D10,
    experience: "13 years",
    qualifications: "MBBS, MS (ENT), DLO",
    location: "Marathahalli, Bangalore",
    about: "ENT and Head & Neck Surgeon specialized in endoscopic sinus surgery, micro ear surgeries, and allergic rhinitis.",
    fee: 650,
    price: 650,
    available: true,
    availability: "Available",
    patients: "3.4k+",
    rating: 4.7,
    email: "deepa.r@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b82611b",
    _id: "6a3820c82cecc9714b82611b",
    name: "Dr. Ishaan Khanna",
    specialization: "Pulmonologist",
    speciality: "Pulmonologist",
    image: D6,
    imageUrl: D6,
    experience: "12 years",
    qualifications: "MBBS, MD (Pulmonary Medicine), FCCP",
    location: "Electronic City, Bangalore",
    about: "Chest specialist treating bronchial asthma, COPD, post-viral respiratory recovery, and sleep apnea.",
    fee: 750,
    price: 750,
    available: true,
    availability: "Available",
    patients: "2.6k+",
    rating: 4.7,
    email: "ishaan.khanna@medicare.com",
  },
  {
    id: "6a3820c82cecc9714b82611c",
    _id: "6a3820c82cecc9714b82611c",
    name: "Dr. Kabir Malhotra",
    specialization: "Gastroenterologist",
    speciality: "Gastroenterologist",
    image: D12,
    imageUrl: D12,
    experience: "17 years",
    qualifications: "MBBS, MD (Medicine), DM (Gastroenterology)",
    location: "JP Nagar, Bangalore",
    about: "Senior Gastroenterologist and Hepatologist performing therapeutic endoscopy, colonoscopy, and fatty liver therapies.",
    fee: 950,
    price: 950,
    available: true,
    availability: "Available",
    patients: "3.8k+",
    rating: 4.8,
    email: "kabir.malhotra@medicare.com",
  },
];
