// src/data/doctorsData.js — Admin Demo Indian Doctors (Bangalore Practo Dataset)

export const INITIAL_DOCTORS = [
  {
    id: 1,
    name: "Dr. Rajesh Kumar",
    specialization: "Cardiologist",
    image: "/assets/D6.png",
    status: "available",
    available: true,
    experience: "16 years",
    qualifications: "MBBS, MD (Cardiology)",
    location: "Indiranagar, Bangalore",
    about:
      "Expert in heart rhythm, cardiac care, and coronary interventions. Focused on patient-first care and minimally invasive procedures.",
    fee: 800,
    schedule: {
      "today": ["09:00 AM", "10:00 AM", "11:30 AM", "12:30 PM"],
      "tomorrow": ["02:00 PM", "03:30 PM", "05:00 PM"],
    },
    patients: "3.5k+",
    rating: 4.9,
  },
  {
    id: 2,
    name: "Dr. Priya Sharma",
    specialization: "Dermatologist",
    image: "/assets/HD5.png",
    status: "available",
    available: true,
    experience: "10 years",
    qualifications: "MBBS, MD (Dermatology)",
    location: "HSR Layout, Bangalore",
    about:
      "Specialist in acne, psoriasis, and cosmetic dermatology with a gentle, patient-first approach.",
    fee: 700,
    schedule: {
      "today": ["09:30 AM", "11:00 AM", "02:00 PM"],
    },
    patients: "2.9k+",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Dr. Vikram Hegde",
    specialization: "Orthopedic Surgeon",
    image: "/assets/D8.png",
    status: "available",
    available: true,
    experience: "18 years",
    qualifications: "MBBS, MS (Orthopedics)",
    location: "Jayanagar, Bangalore",
    about: "Hip and knee replacements, robotic joint surgeries, sports injuries, and trauma care.",
    fee: 1000,
    schedule: {
      "today": ["11:00 AM", "02:30 PM"],
      "tomorrow": ["09:00 AM", "12:00 PM", "03:00 PM"],
    },
    patients: "3.1k+",
    rating: 4.7,
  },
  {
    id: 4,
    name: "Dr. Ananya Deshmukh",
    specialization: "Pediatrician",
    image: "/assets/D4.png",
    status: "available",
    available: true,
    experience: "11 years",
    qualifications: "MBBS, MD (Pediatrics), DCH",
    location: "Whitefield, Bangalore",
    about: "Child growth, developmental milestones, neonatal care, and immunization specialist.",
    fee: 600,
    schedule: {
      "today": ["09:00 AM", "10:30 AM", "04:00 PM"],
    },
    patients: "4.2k+",
    rating: 4.9,
  },
  {
    id: 5,
    name: "Dr. Suresh Reddy",
    specialization: "Neurologist",
    image: "/assets/D7.png",
    status: "available",
    available: true,
    experience: "15 years",
    qualifications: "MBBS, DM (Neurology)",
    location: "Koramangala, Bangalore",
    about: "Chronic migraine relief, stroke recovery, epilepsy management, and neuromuscular care.",
    fee: 900,
    schedule: {
      "today": ["10:00 AM", "01:00 PM", "04:30 PM"],
    },
    patients: "2.8k+",
    rating: 4.8,
  },
  {
    id: 6,
    name: "Dr. Sunita Kulkarni",
    specialization: "Gynecologist",
    image: "/assets/D5.png",
    status: "available",
    available: true,
    experience: "16 years",
    qualifications: "MBBS, MS (OBGYN), DGO",
    location: "Bellandur, Bangalore",
    about: "Antenatal care, high-risk pregnancy, PCOS therapy, and advanced laparoscopic surgeries.",
    fee: 750,
    schedule: {
      "today": ["09:30 AM", "11:30 AM", "03:00 PM"],
    },
    patients: "4.5k+",
    rating: 4.9,
  },
  {
    id: 7,
    name: "Dr. Karthik Venkatesh",
    specialization: "General Physician",
    image: "/assets/D12.png",
    status: "available",
    available: true,
    experience: "12 years",
    qualifications: "MBBS, MD (Internal Medicine)",
    location: "BTM Layout, Bangalore",
    about: "Comprehensive internal medicine, diabetes management, viral fevers, and preventive checkups.",
    fee: 500,
    schedule: {
      "today": ["09:00 AM", "11:00 AM", "05:00 PM"],
    },
    patients: "5.1k+",
    rating: 4.8,
  },
];
